// generated from @vscode/web-custom-data package

// generated from @vscode/web-custom-data package
import type {
  //AttributeConfig,
  TagConfig,
} from 'prism-code-editor/autocomplete';

//const attrValueBool = ['true', 'false'];
//const attrValueBoolNull = ['true', 'false', 'null'];

//const empty: AttributeConfig = {};

// FIXME: import from generated list of functions/sections/etc.
const brindilleTags: TagConfig = {
  if: {},
  else: {},
  elseif: {},
  '/if': {},
  literal: {},
  '/literal': {},
  '#call': {},
  '#load': {},
  '#list': {},
  '#categories': {},
  '#articles': {},
  '#pages': {},
  '#breadcrumbs': {},
  '#images': {},
  '#documents': {},
  '#attachments': {},
  '#users': {},
  '#subscriptions': {},
  '#transactions': {},
  '#transaction_lines': {},
  '#transaction_users': {},
  '#accounts': {},
  '#balances': {},
  '#years': {},
  '#projects': {},
  '#sql': {},
  '#restrict': {},
  '#module': {},
  '#extension': {},
  '#files': {},
  '#foreach': {
    count: null,
    from: null,
    item: null,
    key: null,
  },
  '/call': {},
  '/load': {},
  '/list': {},
  '/categories': {},
  '/articles': {},
  '/pages': {},
  '/breadcrumbs': {},
  '/images': {},
  '/documents': {},
  '/attachments': {},
  '/users': {},
  '/subscriptions': {},
  '/transactions': {},
  '/transaction_lines': {},
  '/transaction_users': {},
  '/accounts': {},
  '/balances': {},
  '/years': {},
  '/projects': {},
  '/sql': {},
  '/restrict': {},
  '/module': {},
  '/extension': {},
  '/files': {},
  '/foreach': {},
  ':include': {},
  ':http': {},
  ':error': {},
  ':read': {},
  ':save': {},
  ':delete': {},
  ':admin_header': {},
  ':admin_footer': {},
  ':password_input': {},
  ':signature': {},
  ':captcha': {},
  ':mail': {},
  ':button': {},
  ':delete_form': {},
  ':form_errors': {},
  ':admin_files': {},
  ':delete_file': {},
  ':api': {},
  ':csv': {},
  ':call': {},
  ':input': {},
  ':link': {},
  ':icon': {},
  ':linkbutton': {},
  ':linkmenu': {},
  ':exportmenu': {},
  ':edit_user_field': {},
  ':user_field': {},
  ':tag': {},
  ':dropdown': {},
  ':debug': {},
  ':assign': {
    var: null,
    append: null,
    from: null,
    value: null,
  },
};

export { brindilleTags };
